# Generated by Django 4.1.7 on 2023-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(db_index=True, default='tell us something Max', max_length=230, verbose_name='body'),
        ),
    ]
